production:
  adapter: postgresql
  database: reuknighted_production
  pool: 100
#  host: localhost
#  port: 5432


development:
  adapter: postgresql
  database: reuknighted_development
#  host: localhost
#  port: 5432

test: &test
  adapter: postgresql
  database: reuknighted_test
#  host: localhost
#  port: 5432

cucumber:
  <<: *test
